services:
  - type: web
    name: tripmate-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: WEATHER_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        sync: false
